services:
  halt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: halt-app
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - vtk-network

networks:
  vtk-network:
    driver: bridge

